# Generated by Django 3.2.8 on 2021-10-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211023_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='returned',
            field=models.IntegerField(default=0),
        ),
    ]
