# Generated by Django 3.2.8 on 2021-10-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_reservation_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
