name: LMS Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.10]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd system
        printf "SECRET_KEY=(_+0q+4@tz(#jl)uk)mm_=u=xz)d=nl_l&_+l9*-d=-*bzww\nDEBUG=False\nALLOWED_HOSTS=127.0.0.1\n" > .env
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd system
        python manage.py migrate
        python manage.py create_groups
        python manage.py test
